### ISSUE TITLE
NPE when calling DeepLinkDelegate.dispatchFrom(this);

### ISSUE THREAD

**Issue by leonardo2204** [airbnb/DeepLinkDispatch#134]
Hello,

I'm getting a NPE when calling `DeepLinkDelegate.dispatchFrom(this);` from my SplashAcitivity.
My code:

```java
@DeepLinkHandler
public class SplashActivity extends BaseActivity implements Updater.UpdaterListener {
...
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_splash);
        DeepLinkDelegate.dispatchFrom(this);
    }
...
}
```

```java
Process: br.com.dinda.qa, PID: 
java.lang.RuntimeException: Unable to start activity ComponentInfo{br.com.dinda.qa/br.com.dinda.views.activities.SplashActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
   at android.app.ActivityThread.-wrap11(ActivityThread.java)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:148)
   at android.app.ActivityThread.main(ActivityThread.java:5417)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
   at com.airbnb.deeplinkdispatch.DeepLinkDelegate.notifyListener(DeepLinkDelegate.java:101)
   at com.airbnb.deeplinkdispatch.DeepLinkDelegate.createResultAndNotify(DeepLinkDelegate.java:94)
   at com.airbnb.deeplinkdispatch.DeepLinkDelegate.dispatchFrom(DeepLinkDelegate.java:31)
   at br.com.dinda.views.activities.SplashActivity.onCreate(SplashActivity.java:37)
   at android.app.Activity.performCreate(Activity.java:6237)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
   at android.app.ActivityThread.-wrap11(ActivityThread.java) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
   at android.os.Handler.dispatchMessage(Handler.java:102) 
   at android.os.Looper.loop(Looper.java:148) 
   at android.app.ActivityThread.main(ActivityThread.java:5417) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

Doing some digging I think I found the problem. On DeepLinkDelegate(L:30) we have:
```java
if (uri == null) {
      return createResultAndNotify(activity, false, null, "No Uri in given activity's intent.");
    }
```
which calls:
```java
private static DeepLinkResult createResultAndNotify(Context context, final boolean successful, final Uri uri, final String error) {
    DeepLinkResult result = new DeepLinkResult(successful, uri, error);
    notifyListener(context, !successful, uri, error);
    return result;
  }
```
which finally calls:
```java
private static void notifyListener(Context context, boolean isError, Uri uri, String errorMessage) {
    Intent intent = new Intent();
    intent.setAction(DeepLinkHandler.ACTION);
    intent.putExtra(DeepLinkHandler.EXTRA_URI, uri.toString());
    intent.putExtra(DeepLinkHandler.EXTRA_SUCCESSFUL, !isError);
    if (isError) {
      intent.putExtra(DeepLinkHandler.EXTRA_ERROR_MESSAGE, errorMessage);
    }
    LocalBroadcastManager.getInstance(context).sendBroadcast(intent);
  }
```

I'm on version 2.0.1 !

So, I'm guessing that after veryfying if Uri is null, the code shouldn't be calling notifyListener, am I right ?

P.S: The awkward part is that according to [this](https://github.com/airbnb/DeepLinkDispatch/blob/master/deeplinkdispatch-processor/src/main/java/com/airbnb/deeplinkdispatch/DeepLinkProcessor.java#L283) the `uri != null` should be generated.

Thanks

**Comment by felipecsl** [comment]
@leonardo2204 this has been fixed here: https://github.com/airbnb/DeepLinkDispatch/commit/a7bc5358a511761e50056638829d6e9db725bea6

However It's not released yet, you can use the snapshot version in the meantime or wait for the next release (which is coming soon!)

**Comment by leonardo2204** [comment]
@felipecsl Should have diff'ed haha.
Thanks for the heads up, I'll wait then !
