### ISSUE TITLE
TaskStackBuilder not created

### ISSUE THREAD

**Issue by jonandersen** [airbnb/DeepLinkDispatch#163]
Currently I'm trying to use the TaskStackBuilder method, but i'm getting a class cast exception:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{co.and.andco.development/co.and.andco.SplashActivity}: java.lang.ClassCastException: android.app.TaskStackBuilder cannot be cast to android.content.Intent
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                              at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                           Caused by: java.lang.ClassCastException: android.app.TaskStackBuilder cannot be cast to android.content.Intent
                                                                              at co.and.andco.DeepLinkDelegate.dispatchFrom(DeepLinkDelegate.java:104)
                                                                              at co.and.andco.DeepLinkDelegate.dispatchFrom(DeepLinkDelegate.java:50)
                                                                              at co.and.andco.SplashActivity.onStart(SplashActivity.java:43)
                                                                              at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
                                                                              at android.app.Activity.performStart(Activity.java:6696)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                              at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:154) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Digging into the crash:

```
  method = c.getMethod(entry.getMethod(), Context.class);
            if (method.getReturnType().equals(TaskStackBuilder.class)) {
              taskStackBuilder = (TaskStackBuilder) method.invoke(c, activity);
              if (taskStackBuilder.getIntentCount() == 0) {
                return createResultAndNotify(activity, false, uri, "Could not deep link to method: " + entry.getMethod() + " intents length == 0" );
              }
              newIntent = taskStackBuilder.editIntentAt(taskStackBuilder.getIntentCount()-1);
            } else {
              newIntent = (Intent) method.invoke(c, activity);
            }
```

It seems that the TaskStackBuilder has to be from the support library. Is it possible to relax this check or add a different error message?

**Comment by felipecsl** [comment]
Indeed this needs a better error message. Thanks for the feedback!
